(() => {
'use strict';
const $ = id => document.getElementById(id);
const canvas = $('canvas'), ctx = canvas.getContext('2d');
let dpr = Math.max(1, window.devicePixelRatio || 1);
const state = {nodes:[],members:[], tool:'select', selected:null, memberStart:null, nextNode:1,nextMember:1, view:{scale:55,ox:120,oy:500}, dragging:null, panning:null, hover:null, results:null, resultTab:'summary'};
let undoStack=[], redoStack=[];
function cloneModel(){return JSON.parse(JSON.stringify({nodes:state.nodes,members:state.members,nextNode:state.nextNode,nextMember:state.nextMember,view:state.view}));}
function pushHistory(){undoStack.push(cloneModel()); if(undoStack.length>100)undoStack.shift(); redoStack=[]; updateButtons();}
function restore(s){state.nodes=s.nodes||[];state.members=s.members||[];state.nextNode=s.nextNode||1;state.nextMember=s.nextMember||1;state.view=s.view||state.view;state.selected=null;state.memberStart=null;state.results=null;render();updateUI();renderResults();}
function undo(){if(!undoStack.length)return;redoStack.push(cloneModel());restore(undoStack.pop());}
function redo(){if(!redoStack.length)return;undoStack.push(cloneModel());restore(redoStack.pop());}
function updateButtons(){$('undoBtn').disabled=!undoStack.length;$('redoBtn').disabled=!redoStack.length;}
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.max(1,devicePixelRatio||1);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0); if(!state.view.oy || state.view.oy>r.height+200)state.view.oy=r.height-70; render();}
const worldToScreen=(x,y)=>({x:state.view.ox+x*state.view.scale,y:state.view.oy-y*state.view.scale});
const screenToWorld=(x,y)=>({x:(x-state.view.ox)/state.view.scale,y:(state.view.oy-y)/state.view.scale});
function pointerPos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
function snap(v){const g=Math.max(.1,Number($('gridSize').value)||1);return $('snapToggle').checked?Math.round(v/g)*g:v;}
function snapPoint(p){return{x:snap(p.x),y:snap(p.y)}}
function nodeAt(sx,sy,tol=10){let best=null,bd=tol;for(const n of state.nodes){const p=worldToScreen(n.x,n.y),d=Math.hypot(p.x-sx,p.y-sy);if(d<bd){best=n;bd=d}}return best}
function distSeg(px,py,a,b){const vx=b.x-a.x,vy=b.y-a.y,wx=px-a.x,wy=py-a.y,c1=vx*wx+vy*wy;if(c1<=0)return Math.hypot(px-a.x,py-a.y);const c2=vx*vx+vy*vy;if(c2<=c1)return Math.hypot(px-b.x,py-b.y);const t=c1/c2;return Math.hypot(px-(a.x+t*vx),py-(a.y+t*vy));}
function memberAt(sx,sy,tol=7){for(let i=state.members.length-1;i>=0;i--){const m=state.members[i],ni=state.nodes.find(n=>n.id===m.i),nj=state.nodes.find(n=>n.id===m.j);if(!ni||!nj)continue;const a=worldToScreen(ni.x,ni.y),b=worldToScreen(nj.x,nj.y);if(distSeg(sx,sy,a,b)<tol)return m}return null}
function setTool(t){state.tool=t;state.memberStart=null;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));const names={select:'ເລືອກ',pan:'ເລື່ອນ',node:'ເພີ່ມ Node',member:'ເພີ່ມ Member',support:'ກຳນົດ Support',load:'ໃສ່ Load'};$('modeLabel').textContent='ໂໝດ: '+names[t];canvas.style.cursor=t==='pan'?'grab':t==='select'?'default':'crosshair';render();}
function invalidate(){state.results=null;renderResults();$('statusText').textContent='ໂມເດວຖືກແກ້ໄຂ — ກະລຸນາວິເຄາະໃໝ່';}
function addNode(x,y){if(state.nodes.some(n=>Math.hypot(n.x-x,n.y-y)<1e-6)){toast('ມີ Node ຢູ່ຈຸດນີ້ແລ້ວ');return null}pushHistory();invalidate();const n={id:state.nextNode++,x,y,support:'none',load:{fx:0,fy:0,mz:0}};state.nodes.push(n);state.selected={type:'node',id:n.id};updateUI();render();return n}
function addMember(i,j){if(i===j)return;if(state.members.some(m=>(m.i===i&&m.j===j)||(m.i===j&&m.j===i))){toast('Member ນີ້ມີແລ້ວ');return}pushHistory();invalidate();const m={id:state.nextMember++,i,j,E:+$('E').value,A:+$('A').value,I:+$('I').value};state.members.push(m);state.selected={type:'member',id:m.id};state.memberStart=null;updateUI();render();}
function deleteSelected(){if(!state.selected)return;pushHistory();invalidate();if(state.selected.type==='node'){const id=state.selected.id;state.nodes=state.nodes.filter(n=>n.id!==id);state.members=state.members.filter(m=>m.i!==id&&m.j!==id)}else state.members=state.members.filter(m=>m.id!==state.selected.id);state.selected=null;updateUI();render();}
function cycleSupport(n){const a=['none','fixed','pin','roller'];n.support=a[(a.indexOf(n.support)+1)%a.length]}
function onDown(e){canvas.setPointerCapture?.(e.pointerId);const p=pointerPos(e);if(e.button===1||e.button===2||state.tool==='pan'||e.code==='Space'){state.panning={x:p.x,y:p.y,ox:state.view.ox,oy:state.view.oy};return}
 const n=nodeAt(p.x,p.y),m=memberAt(p.x,p.y);
 if(state.tool==='node'){const w=snapPoint(screenToWorld(p.x,p.y));addNode(w.x,w.y);return}
 if(state.tool==='member'){if(!n){toast('ກະລຸນາຄລິກທີ່ Node');return}if(!state.memberStart){state.memberStart=n.id;state.selected={type:'node',id:n.id};toast('ເລືອກ Node ທີສອງ');render()}else addMember(state.memberStart,n.id);return}
 if(state.tool==='support'){if(!n){toast('ກະລຸນາຄລິກ Node');return}pushHistory();invalidate();cycleSupport(n);state.selected={type:'node',id:n.id};updateUI();render();return}
 if(state.tool==='load'){if(!n){toast('ກະລຸນາຄລິກ Node');return}const val=prompt('ໃສ່ແຮງ Fy (kN), ຄ່າລົບ = ລົງ', String(n.load.fy||-10));if(val!==null&&!Number.isNaN(Number(val))){pushHistory();invalidate();n.load.fy=Number(val);state.selected={type:'node',id:n.id};updateUI();render()}return}
 if(state.tool==='select'){if(n){state.selected={type:'node',id:n.id};state.dragging={id:n.id,start:cloneModel()};}else if(m){state.selected={type:'member',id:m.id}}else state.selected=null;updateUI();render()}}
function onMove(e){const p=pointerPos(e),w=screenToWorld(p.x,p.y);$('coords').textContent=`X: ${w.x.toFixed(2)}, Y: ${w.y.toFixed(2)} m`;if(state.panning){state.view.ox=state.panning.ox+(p.x-state.panning.x);state.view.oy=state.panning.oy+(p.y-state.panning.y);render();return}if(state.dragging){const n=state.nodes.find(x=>x.id===state.dragging.id),q=snapPoint(w);n.x=q.x;n.y=q.y;state.results=null;render();updateUI();return}state.hover=nodeAt(p.x,p.y)?.id||null;render(p)}
function onUp(){if(state.dragging){undoStack.push(state.dragging.start);redoStack=[];state.dragging=null;updateButtons()}state.panning=null}
function onWheel(e){e.preventDefault();const p=pointerPos(e),before=screenToWorld(p.x,p.y),factor=e.deltaY<0?1.12:1/1.12;state.view.scale=Math.min(250,Math.max(15,state.view.scale*factor));state.view.ox=p.x-before.x*state.view.scale;state.view.oy=p.y+before.y*state.view.scale;render()}
function drawGrid(w,h){if(!$('gridToggle').checked)return;const g=Math.max(.1,Number($('gridSize').value)||1),step=g*state.view.scale;if(step<8)return;ctx.save();ctx.strokeStyle='#e8edf4';ctx.lineWidth=1;let x=((state.view.ox%step)+step)%step;for(;x<w;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}let y=((state.view.oy%step)+step)%step;for(;y<h;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
function drawSupport(n,p){ctx.save();ctx.strokeStyle='#0a356d';ctx.fillStyle='#fff';ctx.lineWidth=2;if(n.support==='fixed'){ctx.beginPath();ctx.moveTo(p.x-12,p.y+8);ctx.lineTo(p.x+12,p.y+8);ctx.stroke();for(let x=-10;x<=10;x+=5){ctx.beginPath();ctx.moveTo(p.x+x,p.y+8);ctx.lineTo(p.x+x-4,p.y+14);ctx.stroke()}}else if(n.support==='pin'||n.support==='roller'){ctx.beginPath();ctx.moveTo(p.x,p.y+4);ctx.lineTo(p.x-10,p.y+18);ctx.lineTo(p.x+10,p.y+18);ctx.closePath();ctx.stroke();if(n.support==='roller'){ctx.beginPath();ctx.arc(p.x-5,p.y+22,3,0,Math.PI*2);ctx.arc(p.x+5,p.y+22,3,0,Math.PI*2);ctx.stroke()}}ctx.restore()}
function drawLoad(n,p){if(!n.load||!n.load.fy)return;const up=n.load.fy>0,tipY=p.y,tailY=p.y+(up?36:-36);ctx.save();ctx.strokeStyle='#e1261c';ctx.fillStyle='#e1261c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,tailY);ctx.lineTo(p.x,tipY);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x,tipY);ctx.lineTo(p.x-5,tipY+(up?8:-8));ctx.lineTo(p.x+5,tipY+(up?8:-8));ctx.closePath();ctx.fill();ctx.font='12px Arial';ctx.fillText(`${n.load.fy} kN`,p.x+7,tailY);ctx.restore()}
function render(mouse){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,r.height);drawGrid(r.width,r.height);
 ctx.save();ctx.strokeStyle='#111827';ctx.lineWidth=2;for(const m of state.members){const aN=state.nodes.find(n=>n.id===m.i),bN=state.nodes.find(n=>n.id===m.j);if(!aN||!bN)continue;const a=worldToScreen(aN.x,aN.y),b=worldToScreen(bN.x,bN.y);ctx.strokeStyle=state.selected?.type==='member'&&state.selected.id===m.id?'#f29b00':'#1f2937';ctx.lineWidth=state.selected?.type==='member'&&state.selected.id===m.id?4:2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.fillStyle='#5b6472';ctx.font='11px Arial';ctx.fillText(`M${m.id}`,(a.x+b.x)/2+4,(a.y+b.y)/2-4)}ctx.restore();
 for(const n of state.nodes){const p=worldToScreen(n.x,n.y);drawSupport(n,p);drawLoad(n,p);ctx.beginPath();ctx.arc(p.x,p.y,(state.selected?.type==='node'&&state.selected.id===n.id)?7:5,0,Math.PI*2);ctx.fillStyle=(state.selected?.type==='node'&&state.selected.id===n.id)?'#f29b00':(state.hover===n.id?'#44a3ff':'#0b5bd3');ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle='#0b4fb0';ctx.font='bold 12px Arial';ctx.fillText(String(n.id),p.x+8,p.y-8)}
 if(state.tool==='member'&&state.memberStart&&mouse){const n=state.nodes.find(x=>x.id===state.memberStart),a=worldToScreen(n.x,n.y);ctx.save();ctx.setLineDash([6,5]);ctx.strokeStyle='#e99a00';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(mouse.x,mouse.y);ctx.stroke();ctx.restore()}
 if(state.results&&$('viewResult').value==='deformed')drawDeformed();
 if(state.results&&$('viewResult').value==='moment')drawMoment();} 

function zeros(n,m){return Array.from({length:n},()=>Array(m).fill(0))}
function matMul(A,B){const r=A.length,c=B[0].length,k=B.length,R=zeros(r,c);for(let i=0;i<r;i++)for(let j=0;j<c;j++)for(let q=0;q<k;q++)R[i][j]+=A[i][q]*B[q][j];return R}
function transpose(A){return A[0].map((_,j)=>A.map(r=>r[j]))}
function matVec(A,v){return A.map(r=>r.reduce((s,x,i)=>s+x*v[i],0))}
function solveLinear(A,b){
 if(!A.length)return[];
 const scale=Math.max(1,...A.flat().map(Math.abs));
 const tol=scale*1e-12;
 A=A.map((r,i)=>[...r,b[i]]);const n=A.length;
 for(let k=0;k<n;k++){
  let p=k;for(let i=k+1;i<n;i++)if(Math.abs(A[i][k])>Math.abs(A[p][k]))p=i;
  if(Math.abs(A[p][k])<tol)throw new Error('Matrix singular: ໂຄງສ້າງບໍ່ສະຖຽນ, Support ບໍ່ພຽງພໍ ຫຼືມີ DOF ທີ່ບໍ່ເຊື່ອມຕໍ່');
  [A[k],A[p]]=[A[p],A[k]];
  for(let i=k+1;i<n;i++){const f=A[i][k]/A[k][k];if(Math.abs(f)<1e-20)continue;for(let j=k;j<=n;j++)A[i][j]-=f*A[k][j]}
 }
 const x=Array(n).fill(0);for(let i=n-1;i>=0;i--){let s=A[i][n];for(let j=i+1;j<n;j++)s-=A[i][j]*x[j];x[i]=s/A[i][i]}
 return x
}
function elementData(m){const ni=state.nodes.find(n=>n.id===m.i),nj=state.nodes.find(n=>n.id===m.j),dx=nj.x-ni.x,dy=nj.y-ni.y,L=Math.hypot(dx,dy);if(L<1e-8)throw new Error('Member ມີຄວາມຍາວເທົ່າ 0');const c=dx/L,s=dy/L,EA=m.E*m.A,EI=m.E*m.I;const k=[[EA/L,0,0,-EA/L,0,0],[0,12*EI/L**3,6*EI/L**2,0,-12*EI/L**3,6*EI/L**2],[0,6*EI/L**2,4*EI/L,0,-6*EI/L**2,2*EI/L],[-EA/L,0,0,EA/L,0,0],[0,-12*EI/L**3,-6*EI/L**2,0,12*EI/L**3,-6*EI/L**2],[0,6*EI/L**2,2*EI/L,0,-6*EI/L**2,4*EI/L]];const T=[[c,s,0,0,0,0],[-s,c,0,0,0,0],[0,0,1,0,0,0],[0,0,0,c,s,0],[0,0,0,-s,c,0],[0,0,0,0,0,1]];return{ni,nj,L,c,s,k,T,kg:matMul(transpose(T),matMul(k,T))}}
function restraints(n){if(n.support==='fixed')return[1,1,1];if(n.support==='pin')return[1,1,0];if(n.support==='roller')return[0,1,0];return[0,0,0]}
function validateModel(){
 if(state.nodes.length<2||!state.members.length)throw new Error('ຕ້ອງມີ Node ແລະ Member');
 const ids=new Set(state.nodes.map(n=>n.id));
 const connected=new Set();
 for(const m of state.members){
  if(!ids.has(m.i)||!ids.has(m.j))throw new Error(`Member ${m.id} ອ້າງອີງ Node ທີ່ບໍ່ມີ`);
  if(!(Number(m.E)>0&&Number(m.A)>0&&Number(m.I)>0))throw new Error(`Member ${m.id}: E, A ແລະ I ຕ້ອງຫຼາຍກວ່າ 0`);
  connected.add(m.i);connected.add(m.j)
 }
 const loose=state.nodes.filter(n=>!connected.has(n.id));
 if(loose.length)throw new Error('ພົບ Node ທີ່ບໍ່ເຊື່ອມ Member: '+loose.map(n=>n.id).join(', '));
 if(!state.nodes.some(n=>n.support!=='none'))throw new Error('ກະລຸນາກຳນົດ Support');
}
function analyze(){try{
 validateModel();
 const index=new Map(state.nodes.map((n,i)=>[n.id,i]));const nd=state.nodes.length*3,K=zeros(nd,nd),F=Array(nd).fill(0),els=[];
 for(const n of state.nodes){const q=index.get(n.id)*3;F[q]=Number(n.load?.fx||0);F[q+1]=Number(n.load?.fy||0);F[q+2]=Number(n.load?.mz||0)}
 for(const m of state.members){const e=elementData(m),ii=index.get(m.i)*3,jj=index.get(m.j)*3,dofs=[ii,ii+1,ii+2,jj,jj+1,jj+2];for(let a=0;a<6;a++)for(let b=0;b<6;b++)K[dofs[a]][dofs[b]]+=e.kg[a][b];els.push({...e,m,dofs})}
 const fixed=[];for(const n of state.nodes){const q=index.get(n.id)*3;restraints(n).forEach((v,i)=>{if(v)fixed.push(q+i)})}
 const free=Array.from({length:nd},(_,i)=>i).filter(i=>!fixed.includes(i));if(!free.length)throw new Error('ບໍ່ມີ Free DOF ໃຫ້ວິເຄາະ');
 const Kff=free.map(i=>free.map(j=>K[i][j])),Ff=free.map(i=>F[i]),uf=solveLinear(Kff,Ff),D=Array(nd).fill(0);free.forEach((d,i)=>D[d]=uf[i]);
 const KD=matVec(K,D),R=KD.map((x,i)=>x-F[i]);
 const memberForces=els.map(e=>{const dg=e.dofs.map(d=>D[d]),dl=matVec(e.T,dg),q=matVec(e.k,dl);return{id:e.m.id,i:e.m.i,j:e.m.j,L:e.L,local:q}});
 const residual=free.length?Math.max(...free.map(i=>Math.abs(KD[i]-F[i]))):0;
 const applied={fx:state.nodes.reduce((s,n)=>s+Number(n.load?.fx||0),0),fy:state.nodes.reduce((s,n)=>s+Number(n.load?.fy||0),0),mz:state.nodes.reduce((s,n)=>s+Number(n.load?.mz||0),0)};
 const reactions={fx:state.nodes.reduce((s,n)=>s+R[index.get(n.id)*3],0),fy:state.nodes.reduce((s,n)=>s+R[index.get(n.id)*3+1],0),mz:state.nodes.reduce((s,n)=>s+R[index.get(n.id)*3+2],0)};
 state.results={D,R,K,F,index,memberForces,maxDisp:Math.max(...D.map(Math.abs)),analyzedAt:new Date().toISOString(),freeDof:free.length,fixedDof:fixed.length,residual,applied,reactions};
 $('statusText').textContent='ວິເຄາະສຳເລັດ • Residual '+residual.toExponential(2);renderResults();render();toast('ວິເຄາະສຳເລັດ')
 }catch(err){console.error(err);alert(err.message);$('statusText').textContent='ວິເຄາະບໍ່ສຳເລັດ'}}
const fmt=(v,d=5)=>Math.abs(v)<1e-10?'0':Number(v).toFixed(d);
function renderResults(){const box=$('resultContent');if(!state.results){box.innerHTML='<div class="empty">ຍັງບໍ່ມີຜົນວິເຄາະ</div>';return}const r=state.results;if(state.resultTab==='summary'){box.innerHTML=`<div class="metric-grid"><div class="metric">Max displacement<b>${fmt(r.maxDisp*1000,3)} mm</b></div><div class="metric">Free / Fixed DOF<b>${r.freeDof} / ${r.fixedDof}</b></div><div class="metric">Solver residual<b>${Number(r.residual).toExponential(2)}</b></div><div class="metric">Node / Member<b>${state.nodes.length} / ${state.members.length}</b></div></div><div class="equilibrium"><b>Global equilibrium check</b><span>ΣFx = ${fmt(r.applied.fx+r.reactions.fx,6)} kN</span><span>ΣFy = ${fmt(r.applied.fy+r.reactions.fy,6)} kN</span><span>ΣMz* = ${fmt(r.applied.mz+r.reactions.mz,6)} kN·m</span><small>*ΣMz ນີ້ແມ່ນຜົນລວມ nodal moments/reaction moments; ບໍ່ລວມ moment arm ຂອງ nodal forces.</small></div>`;return}if(state.resultTab==='disp'){box.innerHTML='<table><tr><th>Node</th><th>Ux (mm)</th><th>Uy (mm)</th><th>Rz (rad)</th></tr>'+state.nodes.map(n=>{const q=r.index.get(n.id)*3;return`<tr><td>${n.id}</td><td>${fmt(r.D[q]*1000,4)}</td><td>${fmt(r.D[q+1]*1000,4)}</td><td>${fmt(r.D[q+2],7)}</td></tr>`}).join('')+'</table>';return}if(state.resultTab==='react'){box.innerHTML='<table><tr><th>Node</th><th>Rx (kN)</th><th>Ry (kN)</th><th>Mz (kN·m)</th></tr>'+state.nodes.filter(n=>n.support!=='none').map(n=>{const q=r.index.get(n.id)*3;return`<tr><td>${n.id}</td><td>${fmt(r.R[q],4)}</td><td>${fmt(r.R[q+1],4)}</td><td>${fmt(r.R[q+2],4)}</td></tr>`}).join('')+'</table>';return}box.innerHTML='<table><tr><th>Member</th><th>Ni</th><th>Vi</th><th>Mi</th><th>Nj</th><th>Vj</th><th>Mj</th></tr>'+r.memberForces.map(x=>`<tr><td>${x.id}</td>${x.local.map(v=>`<td>${fmt(v,4)}</td>`).join('')}</tr>`).join('')+'</table>'}
function drawDeformed(){const r=state.results;if(!r)return;const max=r.maxDisp||1,fac=Math.min(200,Math.max(1,60/(max*state.view.scale||1)));ctx.save();ctx.setLineDash([7,4]);ctx.strokeStyle='#1671e8';ctx.lineWidth=2;for(const m of state.members){const ni=state.nodes.find(n=>n.id===m.i),nj=state.nodes.find(n=>n.id===m.j),qi=r.index.get(ni.id)*3,qj=r.index.get(nj.id)*3,a=worldToScreen(ni.x+r.D[qi]*fac,ni.y+r.D[qi+1]*fac),b=worldToScreen(nj.x+r.D[qj]*fac,nj.y+r.D[qj+1]*fac);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.restore()}
function drawMoment(){const r=state.results;if(!r)return;const max=Math.max(1,...r.memberForces.flatMap(x=>[Math.abs(x.local[2]),Math.abs(x.local[5])])),fac=45/max;ctx.save();ctx.strokeStyle='#d12c2c';ctx.fillStyle='#ef444433';ctx.lineWidth=1.5;for(const f of r.memberForces){const ni=state.nodes.find(n=>n.id===f.i),nj=state.nodes.find(n=>n.id===f.j),a=worldToScreen(ni.x,ni.y),b=worldToScreen(nj.x,nj.y),dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy),nx=-dy/L,ny=dx/L,o1=f.local[2]*fac,o2=-f.local[5]*fac;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(a.x+nx*o1,a.y+ny*o1);ctx.lineTo(b.x+nx*o2,b.y+ny*o2);ctx.lineTo(b.x,b.y);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()}
function clearResults(){state.results=null;$('viewResult').value='model';renderResults();render();$('statusText').textContent='ລ້າງຜົນແລ້ວ'}
function cloudClient(){const u=window.SAPUDOM_SUPABASE_URL,k=window.SAPUDOM_SUPABASE_ANON_KEY;if(!u||!k||!window.supabase)return null;return window.supabase.createClient(u,k)}
async function cloudDialog(){const sb=cloudClient();if(!sb){alert('Supabase ຍັງບໍ່ໄດ້ຕັ້ງຄ່າ. ໃສ່ Project URL ແລະ Anon Key ໃນ supabase-config.js ແລະ run supabase-setup.sql');return}const wrap=document.createElement('div');wrap.className='cloud-dialog';wrap.innerHTML='<div class="cloud-card"><h2>☁ Supabase Cloud</h2><div id="cloudBody">ກຳລັງໂຫຼດ...</div><button id="cloudClose">ປິດ</button></div>';document.body.appendChild(wrap);wrap.querySelector('#cloudClose').onclick=()=>wrap.remove();const body=wrap.querySelector('#cloudBody');const {data:{session}}=await sb.auth.getSession();if(!session){body.innerHTML='<input id="cloudEmail" type="email" placeholder="Email"><input id="cloudPass" type="password" placeholder="Password"><div class="cloud-actions"><button id="cloudLogin">Login</button><button id="cloudSignup">Sign up</button></div>';const auth=async signup=>{const email=wrap.querySelector('#cloudEmail').value,password=wrap.querySelector('#cloudPass').value;const res=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(res.error)alert(res.error.message);else{wrap.remove();cloudDialog()}};wrap.querySelector('#cloudLogin').onclick=()=>auth(false);wrap.querySelector('#cloudSignup').onclick=()=>auth(true);return}const refresh=async()=>{const {data,error}=await sb.from('structure_projects').select('id,name,updated_at').order('updated_at',{ascending:false});if(error){body.textContent=error.message;return}body.innerHTML='<div class="cloud-actions"><button id="cloudSave">Save current</button><button id="cloudLogout">Logout</button></div><div class="cloud-list">'+data.map(x=>`<div class="cloud-item"><span>${x.name}</span><button data-id="${x.id}">Open</button></div>`).join('')+'</div>';body.querySelector('#cloudSave').onclick=async()=>{const model={projectName:$('projectName').value,units:$('units').value,...cloneModel()};const {error}=await sb.from('structure_projects').insert({owner_id:session.user.id,name:model.projectName,model});if(error)alert(error.message);else refresh()};body.querySelector('#cloudLogout').onclick=async()=>{await sb.auth.signOut();wrap.remove()};body.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{const {data,error}=await sb.from('structure_projects').select('model').eq('id',b.dataset.id).single();if(error)alert(error.message);else{pushHistory();restore(data.model);$('projectName').value=data.model.projectName||'Cloud Project';wrap.remove();toast('ເປີດຈາກ Cloud ແລ້ວ')}})};refresh()}

function updateUI(){$('nodeCount').textContent=state.nodes.length;$('memberCount').textContent=state.members.length;$('supportCount').textContent=state.nodes.filter(n=>n.support!=='none').length;$('loadCount').textContent=state.nodes.filter(n=>n.load&&(n.load.fx||n.load.fy||n.load.mz)).length;let html='ຍັງບໍ່ໄດ້ເລືອກ';if(state.selected?.type==='node'){const n=state.nodes.find(x=>x.id===state.selected.id);if(n)html=`<b>Node ${n.id}</b><br>X = ${n.x.toFixed(3)} m<br>Y = ${n.y.toFixed(3)} m<br>Support: ${n.support}<br>Fy = ${n.load.fy} kN`}if(state.selected?.type==='member'){const m=state.members.find(x=>x.id===state.selected.id);if(m){html=`<b>Member ${m.id}</b><br>Node ${m.i} → ${m.j}<br>E=${m.E}<br>A=${m.A}<br>I=${m.I}`;$('E').value=m.E;$('A').value=m.A;$('I').value=m.I}}$('selectionInfo').innerHTML=html;updateButtons()}
function fit(){if(!state.nodes.length){state.view={scale:55,ox:120,oy:canvas.getBoundingClientRect().height-70};render();return}const r=canvas.getBoundingClientRect(),xs=state.nodes.map(n=>n.x),ys=state.nodes.map(n=>n.y),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),dx=Math.max(2,maxx-minx),dy=Math.max(2,maxy-miny);state.view.scale=Math.min((r.width-140)/dx,(r.height-140)/dy);state.view.scale=Math.max(20,Math.min(120,state.view.scale));state.view.ox=70-minx*state.view.scale;state.view.oy=r.height-70+miny*state.view.scale;render()}
function sample(){pushHistory();invalidate();state.nodes=[{id:1,x:0,y:0,support:'fixed',load:{fx:0,fy:0,mz:0}},{id:2,x:6,y:0,support:'fixed',load:{fx:0,fy:0,mz:0}},{id:3,x:12,y:0,support:'fixed',load:{fx:0,fy:0,mz:0}},{id:4,x:0,y:4,support:'none',load:{fx:0,fy:0,mz:0}},{id:5,x:6,y:4,support:'none',load:{fx:0,fy:-20,mz:0}},{id:6,x:12,y:4,support:'none',load:{fx:0,fy:0,mz:0}},{id:7,x:0,y:8,support:'none',load:{fx:0,fy:0,mz:0}},{id:8,x:6,y:8,support:'none',load:{fx:0,fy:-30,mz:0}},{id:9,x:12,y:8,support:'none',load:{fx:0,fy:0,mz:0}}];const pairs=[[1,4],[4,7],[2,5],[5,8],[3,6],[6,9],[4,5],[5,6],[7,8],[8,9]];state.members=pairs.map((p,i)=>({id:i+1,i:p[0],j:p[1],E:25000000,A:.15,I:.003125}));state.nextNode=10;state.nextMember=11;state.selected=null;updateUI();fit();toast('ສ້າງໂມເດວຕົວຢ່າງແລ້ວ')}
function save(){const data={version:'1.4.1',projectName:$('projectName').value,units:$('units').value,...cloneModel()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=($('projectName').value||'sapudom-project').replace(/[^a-z0-9_-]+/gi,'-')+'.json';a.click();URL.revokeObjectURL(a.href);toast('ບັນທຶກໄຟລ໌ແລ້ວ')}
function openFile(file){const fr=new FileReader();fr.onload=()=>{try{const d=JSON.parse(fr.result);pushHistory();restore(d);$('projectName').value=d.projectName||'Opened Project';$('units').value=d.units||'kN - m';toast('ເປີດໂຄງການແລ້ວ')}catch{alert('ໄຟລ໌ JSON ບໍ່ຖືກຕ້ອງ')}};fr.readAsText(file)}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
document.querySelectorAll('.tool').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
$('deleteBtn').onclick=deleteSelected;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('fitBtn').onclick=fit;$('zoomInBtn').onclick=()=>{state.view.scale*=1.2;render()};$('zoomOutBtn').onclick=()=>{state.view.scale/=1.2;render()};$('sampleBtn').onclick=sample;$('saveBtn').onclick=save;$('openBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>e.target.files[0]&&openFile(e.target.files[0]);$('newBtn').onclick=()=>{if(confirm('ສ້າງໂຄງການໃໝ່?')){pushHistory();invalidate();state.nodes=[];state.members=[];state.nextNode=1;state.nextMember=1;state.selected=null;updateUI();render()}};$('applyPropsBtn').onclick=()=>{if(state.selected?.type!=='member'){toast('ເລືອກ Member ກ່ອນ');return}pushHistory();const m=state.members.find(x=>x.id===state.selected.id);invalidate();m.E=+$('E').value;m.A=+$('A').value;m.I=+$('I').value;updateUI();toast('ນຳໃຊ້ຄ່າແລ້ວ')};['gridToggle','snapToggle','gridSize'].forEach(id=>$(id).addEventListener('change',render));
canvas.addEventListener('pointerdown',onDown);canvas.addEventListener('pointermove',onMove);canvas.addEventListener('pointerup',onUp);canvas.addEventListener('pointercancel',onUp);canvas.addEventListener('wheel',onWheel,{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase();if(k==='v')setTool('select');if(k==='h')setTool('pan');if(k==='n')setTool('node');if(k==='m')setTool('member');if(e.key==='Delete'||e.key==='Backspace')deleteSelected();if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?redo():undo()}});

$('analyzeBtn').onclick=analyze;$('clearResultsBtn').onclick=clearResults;$('cloudBtn').onclick=cloudDialog;$('viewResult').onchange=render;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.resultTab=b.dataset.tab;renderResults()});

resize();updateUI();renderResults();setTool('select');toast('V1.4.1 Analysis Core ພ້ອມໃຊ້ງານ');
})();
